blank_issues_enabled: false
contact_links:
  - name: 💬 Diskussion
    url: https://github.com/jchillah/globalakte/discussions
    about: Allgemeine Fragen und Diskussionen
  - name: 📚 Dokumentation
    url: https://github.com/jchillah/globalakte/wiki
    about: Projekt-Dokumentation und Guides 