name: 🧠 Auto-Zuweisung nach Label

on:
  issues:
    types: [labeled]

jobs:
  assign_by_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set assignee based on label
        run: |
          if [[ "${{ github.event.label.name }}" == "Sprint-1-Setup" ]]; then
            gh issue edit "${{ github.event.issue.number }}" \
              --add-assignee "${{ github.event.issue.user.login }}"
          fi
